// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrLMpM9eaJaTer9KB73_bZb65HBnuSQ3E',
    appId: '1:538569861021:web:d0a00bebf27492b4503174',
    messagingSenderId: '538569861021',
    projectId: 'test-95243',
    authDomain: 'test-95243.firebaseapp.com',
    storageBucket: 'test-95243.appspot.com',
    measurementId: 'G-PKZCSC3QE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxhX9KvXoLbunmRsSU-iDGyjFI-NQZbKM',
    appId: '1:538569861021:android:ddccfd637e41b4e1503174',
    messagingSenderId: '538569861021',
    projectId: 'test-95243',
    storageBucket: 'test-95243.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx0A88hID42yqKA0u9xX3CeP9EYnf3zQ0',
    appId: '1:538569861021:ios:6e1bddd27fbb41ae503174',
    messagingSenderId: '538569861021',
    projectId: 'test-95243',
    storageBucket: 'test-95243.appspot.com',
    iosClientId: '538569861021-ctfph1fese305uksu6399jj00l29qdra.apps.googleusercontent.com',
    iosBundleId: 'com.example.alertYourTask',
  );
}
